version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: myplanner-catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - postgres_catalog:/var/lib/postgresql/data