global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using AutoMapper;
global using BeyondNet.Ddd.Interfaces;
global using Microsoft.EntityFrameworkCore.Storage;
global using System.Data;
global using MediatR;